name: CI

on:
  push:
    branches: [main, develop, devops]
  pull_request:
    branches: [main, develop, devops]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 14
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # Install dependencies
      - run: npm install

      # Run tests
      
      - run: npm test