name: CI

on:
  push:
    branches: [main, develop, devops]
  pull_request:
    branches: [main, develop, devops]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 14
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # Install dependencies
      - name : Npm Install
        run: npm install
        
      - name : Test
        run: npm run test --if-present
        env:
          CI: false
          NODE_OPTIONS: --max_old_space_size=4096
          MONGODB_URL: ${{secrets.MONGODB_URL}}
          JWT_ACCESS_SECRET: ${{secrets.JWT_ACCESS_SECRET}}
          JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
          JWT_RESET_SECRET: ${{secrets.JWT_RESET_SECRET}}
          JWT_CONFIRM_SECRET: ${{secrets.JWT_CONFIRM_SECRET}}
          JWT_ACCESS_EXPIRES_IN: ${{secrets.JWT_ACCESS_EXPIRES_IN}}
          JWT_REFRESH_EXPIRES_IN: ${{secrets.JWT_REFRESH_EXPIRES_IN}}
          JWT_RESET_EXPIRES_IN: ${{secrets.JWT_RESET_EXPIRES_IN}}
          JWT_CONFIRM_EXPIRES_IN: ${{secrets.JWT_CONFIRM_EXPIRES_IN}}
          CLIENT_URL: ${{secrets.CLIENT_URL}}
          SERVER_URL: ${{secrets.SERVER_URL}}
          SERVER_PORT: ${{secrets.SERVER_PORT}}
          MAIL_USER: ${{secrets.MAIL_USER}}
          MAIL_PASS: ${{secrets.MAIL_PASS}}
          MAIL_FIRSTNAME: ${{secrets.MAIL_FIRSTNAME}}
          MAIL_LASTNAME: ${{secrets.MAIL_LASTNAME}}
          GMAIL_CLIENT_ID: ${{secrets.GMAIL_CLIENT_ID}}
          GMAIL_CLIENT_SECRET: ${{secrets.GMAIL_CLIENT_SECRET}}
          GMAIL_REFRESH_TOKEN: ${{secrets.GMAIL_REFRESH_TOKEN}}
          GMAIL_REDIRECT_URI: ${{secrets.GMAIL_REDIRECT_URI}}
          COOKIE_DOMAIN: ${{secrets.COOKIE_DOMAIN}}
          
#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
